from Classification.SingleEvaluation import SingleEvaluationBinary, SingleEvaluationMultiClass
from Classification.CrossValidationEvaluation import CrossValidationEvaluationBinary, \
    CrossValidationEvaluationMultiClass
